name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main

env:
  PYTHON_VERSION: "3.11.14"
  APP_PATH: "src"
  DOCKER_IMAGE_TAG: ""

jobs:
  build:
    runs-on: ${{ vars.FINAL_PROJECT_BASE_IMAGE }}
    steps:

      - 
        name: Checkout repository branch
        uses: actions/checkout@v4

      - 
        name: Set Image Tag
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          BRANCH=${GITHUB_REF_NAME}

          if [ "$BRANCH" = "main" ]; then
            echo "DOCKER_IMAGE_TAG=prod-$SHORT_SHA" >> $GITHUB_ENV
          else
            echo "DOCKER_IMAGE_TAG=$BRANCH-$SHORT_SHA" >> $GITHUB_ENV
          fi

      -
        name: Display variables
        run: |
          echo "BASE_IMAGE: ${{ vars.FINAL_PROJECT_BASE_IMAGE }}"
          echo "PYTHON_VERSION: ${{ env.PYTHON_VERSION }}"
          echo "APP_PATH: ${{ env.APP_PATH }}"
          echo "DOCKER_IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}"

      - 
        name: Checkout repository branch
        uses: actions/checkout@v4

      - 
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      -
        name: Install dependencies
        run: pip install -r "${{ env.APP_PATH }}/requirements.txt"

      -
        name: Run test
        run: pytest "${{ env.APP_PATH }}"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_PATH }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/final-project-backend:${{ env.DOCKER_IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ runner.os }}-buildx
          cache-to: type=gha,scope=${{ runner.os }}-buildx-new,mode=max